import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import Story from "../components/Story";
import { getWebsiteAndData } from "../helpers";
import useStories from "../hooks/useStories";

export default function Home() {
  const [ipt, setIpt] = useState("");
  // TODO Add prev comment count to list
  const [list, setList] = useState([]);
  const [stories] = useStories(list);

  useEffect(() => {
    console.log("render");
  });

  useEffect(() => {
    const prevList = localStorage.getItem("posts");
    if (prevList && prevList.length > 1) {
      // Stories are stored in local storage split by |
      // then grab the id
      const newList = prevList
        .split("|")
        .map((story) => story.split(","))
        .map((el) => el[0]);
      setList(newList);
    }
  }, []);

  useEffect(() => {
    const postsWithComment = stories.map((item) => [item.id, item.descendants]);
    localStorage.setItem("posts", postsWithComment.join("|"));
  }, [stories]);

  const handleForm = (e) => {
    e.preventDefault();
    let webData = getWebsiteAndData(ipt);
    if (webData) {
      setList([...list, webData]);
      setIpt("");
    } else {
      alert("error");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Check Back Later</h1>
        <form onSubmit={handleForm}>
          <input value={ipt} onChange={(e) => setIpt(e.target.value)} />
          <button>Add</button>
        </form>
        {stories.map((story) => (
          <Story key={story.url + Math.random()} post={story} />
        ))}
      </main>
    </div>
  );
}
